### ISSUE TITLE
An interesting power system

### ISSUE THREAD

**Issue by BigCasper** [TyrellPlayz/Big-Industries#11]
Have something more creative then the standard RF/MJ power system. Like Botania, self-contained and well balanced, and like IC2, more complex and sometimes dangerous. Maybe the default power transfering method would be power pylons? Different Voltages would be required to diffrent tired machines along the progression? Just don't use the overdone RF. It's boring.

**Comment by TyrellPlayz** [comment]
RF is the modding communities standard energy. It allows different mods to share energy with each other. Plus it would be so much easier to code as many modders have already coded it.
