### ISSUE TITLE
Crashing when running on server

### ISSUE THREAD

**Issue by Siriuo** [TyrellPlayz/Big-Industries#6]
See crash log at: https://pastebin.com/Gx8zL0SG

**Comment by TyrellPlayz** [comment]
This may be a forge issue. Try running the server with no mods installed. And post any error logs here.

**Comment by Siriuo** [comment]
Server runs fine with no mods installed.
Server also runs fine with other mods installed although I have had some other mods which do cause a similar or same issue mainly anything which seems to interact with the GUI.

**Comment by TyrellPlayz** [comment]
It turns out it was an issue on my end but it was an easy fix.
https://minecraft.curseforge.com/projects/big-industries/files/2696043
