### ISSUE TITLE
Crusher recipe requires invar, which requires a crusher...

### ISSUE THREAD

**Issue by iDarper** [TyrellPlayz/Big-Industries#8]
We recently added this to our pack (Siriuo is the server owner) and just noticed that the crusher requires crushed iron and crushed nickel. Problem here, is those require a crusher to make, so the crusher requires the crusher to make itself.... Maybe an alternate recipe would help.

**Comment by TyrellPlayz** [comment]
Oops. I will fix that.

**Comment by TyrellPlayz** [comment]
Fixed and updated.
https://github.com/TyrellPlayz/Big-Industries/pull/9
https://minecraft.curseforge.com/projects/big-industries/files/2698612
